name: solid_software
description: "Test task from Solid Software"
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.7 <4.0.0"

dependencies:
  auto_route: ^8.1.4
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  injectable: ^2.4.4
  intl: ^0.19.0
  logger: ^2.4.0

dev_dependencies:
  auto_route_generator: ^8.1.0
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  solid_lints: ^0.1.5

flutter:
  uses-material-design: true
